baseurl = "https://tcmenu.github.io/documentation"
languageCode = "en-us"
title = "TcMenu Documentation"
theme = "belter"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    production = "N"
    EnableAds = "N"
    author = "TcMenu"
    refDocsLocation = "https://tcmenu.github.io/documentation/refdocs"
    gitEditURL = "https://github.com/TcMenu/documentation/tree/main/content"

[[menu.main]]
    name = "tcMenu"
    weight = 0
    identifier = "tc-menu"

[[menu.footer]]
    name = "Privacy and terms of use"
    url = "/legal/privacy"
    weight = 1

[[menu.footer]]
    name = "Built by TheCodersCorner"
    url = "https://www.thecoderscorner.com/"
    weight = 2

[[menu.footer]]
    name = "Built on Hugo CMS"
    url = "https://gohugo.io/"
    weight = 3

[params.widgets]
    search = true
    categories = true
    tags = true

[markup.goldmark.renderer]
    unsafe = true
